#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the Dailies Notes Assistant Project.
#
# Bootstrap script for new contributors.
# Checks prerequisites, copies example configs, installs frontend dependencies,
# configures transcription (Vexa bot or browser extension + WhisperLive),
# and starts the full DNA stack.
#
# Usage:
#   ./bootstrap.sh           # first-time setup
#   ./bootstrap.sh --start   # day-to-day: start services without re-running setup
#
# Supported platforms: macOS, Linux

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BACKEND_DIR="$SCRIPT_DIR/backend"
FRONTEND_DIR="$SCRIPT_DIR/frontend"
FRONTEND_ENV="$FRONTEND_DIR/packages/app/.env"

VEXA_ADMIN_URL="http://localhost:8056"
VEXA_ADMIN_TOKEN="your-admin-token"
VEXA_LOCAL_EMAIL="dna-local@example.com"
# Set to "true" when the user chooses hosted Vexa (api.cloud.vexa.ai); the
# local Vexa container and transcription-backend setup are then skipped.
VEXA_HOSTED=false
VEXA_CLOUD_URL="https://api.cloud.vexa.ai"

# Set by choose_transcription_route: "vexa" (default) or "extension"
TRANSCRIPTION_ROUTE="vexa"

# Shared secret tying the browser extension to this DNA instance. Generated by
# configure_extension_transcription and written to both the backend compose file
# and the frontend .env; the user pastes the same value into the extension popup.
EXTENSION_KEY=""

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
BOLD='\033[1m'
NC='\033[0m'

info() { echo -e "${BLUE}[info]${NC}  $*"; }
ok()   { echo -e "${GREEN}[ok]${NC}    $*"; }
warn() { echo -e "${YELLOW}[warn]${NC}  $*"; }
die()  { echo -e "${RED}[error]${NC} $*" >&2; exit 1; }

# ── helpers ────────────────────────────────────────────────────────────────────

get_compose_cmd() {
    if command -v docker-compose &>/dev/null; then
        echo "docker-compose"
    else
        echo "docker compose"
    fi
}

# Back up $dst if it already exists, then copy $src → $dst.
safe_copy() {
    local src="$1" dst="$2"
    if [[ -f "$dst" ]]; then
        rm -f "${dst}".bak.*
        local bak="${dst}.bak.$(date +%Y%m%d%H%M%S)"
        warn "$(basename "$dst") already exists — backed up to $(basename "$bak")"
        cp "$dst" "$bak"
    fi
    cp "$src" "$dst"
    ok "$(basename "$src") → $(basename "$dst")"
}

# In-place sed replacement: replace every occurrence of KEY=<anything> with KEY=VALUE.
# Uses a backup suffix then deletes it, which works on both macOS and Linux.
set_env_var() {
    local key="$1" value="$2" file="$3"
    sed -i.bak "s|${key}=.*|${key}=${value}|g" "$file"
    rm -f "${file}.bak"
}

# Set KEY=VALUE in a compose environment block, appending if the key is absent.
ensure_env_var() {
    local key="$1" value="$2" file="$3"
    if grep -qF "${key}=" "$file" 2>/dev/null; then
        set_env_var "$key" "$value" "$file"
        return
    fi
    python3 - "$file" "$key" "$value" <<'PYEOF'
import sys

path, key, value = sys.argv[1], sys.argv[2], sys.argv[3]
with open(path) as f:
    lines = f.readlines()

last_env_idx = -1
for i, line in enumerate(lines):
    stripped = line.lstrip()
    if stripped.startswith("- ") and "=" in stripped:
        last_env_idx = i

if last_env_idx < 0:
    sys.exit(1)

indent = lines[last_env_idx][: len(lines[last_env_idx]) - len(lines[last_env_idx].lstrip())]
lines.insert(last_env_idx + 1, f"{indent}- {key}={value}\n")
with open(path, "w") as f:
    f.writelines(lines)
PYEOF
}

# Set a frontend VITE_* flag, uncommenting the line if it ships commented out in
# the example .env. Appends the line if the key is not present at all.
set_feature_flag() {
    local key="$1" value="$2" file="$3"
    # Match only a bare assignment line (optionally commented): "KEY=" or
    # "KEY=value" with no trailing prose, so explanatory comments that mention
    # the key are left untouched.
    if grep -qE "^#? *${key}=[^[:space:]]*$" "$file"; then
        sed -i.bak -E "s|^#? *${key}=[^[:space:]]*$|${key}=${value}|" "$file"
        rm -f "${file}.bak"
    else
        printf '%s=%s\n' "$key" "$value" >> "$file"
    fi
}

# Generate a short, random shared key for the extension↔DNA binding.
# 12 hex chars (6 random bytes) — short enough to paste, random enough to gate.
generate_extension_key() {
    python3 -c "import secrets; print(secrets.token_hex(6))"
}

# Read the extension key currently configured for this instance: the value
# generated this run if any, otherwise whatever is in the backend compose file
# (so `--start` and re-runs still report the right key).
current_extension_key() {
    if [[ -n "$EXTENSION_KEY" ]]; then
        echo "$EXTENSION_KEY"
        return
    fi
    grep -E '^[[:space:]]*-?[[:space:]]*DNA_EXTENSION_KEY=' \
        "$BACKEND_DIR/docker-compose.local.yml" 2>/dev/null \
        | tail -n1 \
        | sed -E 's|.*DNA_EXTENSION_KEY=||' \
        | tr -d ' "'
}

# Map a user answer (o/on, f/off, u/blank) to "true", "false", or "" (unset).
normalize_flag() {
    case "$1" in
        o|[oO][nN])   echo "true" ;;
        f|[oO][fF][fF]) echo "false" ;;
        *)            echo "" ;;
    esac
}

# Apply one feature flag: write it to the frontend .env, or report it as left
# user-controlled when the value is empty. $4 is an optional note (e.g. cascade).
apply_feature_flag() {
    local key="$1" label="$2" value="$3" note="${4:-}"
    if [[ -z "$value" ]]; then
        ok "${label} left user-controlled"
        return
    fi
    set_feature_flag "$key" "$value" "$FRONTEND_ENV"
    local state="ON"; [[ "$value" == "false" ]] && state="OFF"
    if [[ -n "$note" ]]; then
        ok "${label} forced ${state} (${note}) in frontend/packages/app/.env"
    else
        ok "${label} forced ${state} in frontend/packages/app/.env"
    fi
}

# ── step 1: prerequisites ──────────────────────────────────────────────────────

check_prerequisites() {
    info "Checking prerequisites..."

    command -v node &>/dev/null \
        || die "Node.js not found. Install Node.js v18+: https://nodejs.org/en/download"
    local node_major
    node_major="$(node --version | sed 's/v//' | cut -d. -f1)"
    [[ "$node_major" -ge 18 ]] \
        || die "Node.js v18+ required (found $(node --version)). Upgrade: https://nodejs.org/en/download"
    ok "Node.js $(node --version)"

    command -v npm &>/dev/null \
        || die "npm not found. Install Node.js v18+: https://nodejs.org/en/download"
    ok "npm $(npm --version)"

    command -v python3 &>/dev/null \
        || die "python3 not found. Install Python 3: https://www.python.org/downloads/"
    ok "python3 $(python3 --version | awk '{print $2}')"

    command -v docker &>/dev/null \
        || die "Docker not found. Install Docker: https://docs.docker.com/get-docker/"
    ok "Docker $(docker --version | awk '{gsub(/,/,"",$3); print $3}')"

    docker info &>/dev/null \
        || die "Docker daemon is not running. Start Docker Desktop (or the service) and try again."
    ok "Docker daemon is running"
}

# ── step 2: copy example config files ─────────────────────────────────────────

copy_config_files() {
    info "Copying example config files..."
    safe_copy \
        "$BACKEND_DIR/example.docker-compose.local.yml" \
        "$BACKEND_DIR/docker-compose.local.yml"
    if [[ "$TRANSCRIPTION_ROUTE" != "extension" ]]; then
        safe_copy \
            "$BACKEND_DIR/example.docker-compose.local.vexa.yml" \
            "$BACKEND_DIR/docker-compose.local.vexa.yml"
    else
        info "Skipping Vexa compose overrides (browser-extension transcription route)"
    fi
    safe_copy \
        "$FRONTEND_DIR/packages/app/.env.example" \
        "$FRONTEND_DIR/packages/app/.env"
}

# ── step 3: LLM provider setup ─────────────────────────────────────────────────

configure_llm() {
    echo ""
    echo -e "${BOLD}LLM provider setup${NC}"
    echo "  (Press Enter on any prompt to skip and fill in manually later)"
    echo ""
    echo "  1) OpenAI  (default)"
    echo "  2) Anthropic (Claude)"
    echo "  3) Gemini"
    echo "  4) Custom  (OpenAI-compatible)"
    echo "  5) Skip"
    echo ""
    read -r -p "  Choice [1]: " llm_choice
    llm_choice="${llm_choice:-1}"
    echo ""

    case "$llm_choice" in
        2|[aA]nthropic|[cC]laude)
            read -r -p "  Anthropic API key: " anthropic_key
            if [[ -n "$anthropic_key" ]]; then
                # The example file has an OPENAI_API_KEY line; replace it with
                # the Anthropic key and insert LLM_PROVIDER=anthropic above it.
                python3 - "$BACKEND_DIR/docker-compose.local.yml" "$anthropic_key" <<'PYEOF'
import sys

path, key = sys.argv[1], sys.argv[2]
with open(path) as f:
    lines = f.readlines()
out = []
for line in lines:
    stripped = line.lstrip()
    if stripped.startswith('- OPENAI_API_KEY='):
        indent = line[: len(line) - len(stripped)]
        out.append(f"{indent}- LLM_PROVIDER=anthropic\n")
        out.append(f"{indent}- ANTHROPIC_API_KEY={key}\n")
        out.append(f"{indent}- ANTHROPIC_MODEL=claude-opus-4-8\n")
    else:
        out.append(line)
with open(path, 'w') as f:
    f.writelines(out)
PYEOF
                ok "Anthropic API key written to backend/docker-compose.local.yml"
            else
                warn "Skipped — set ANTHROPIC_API_KEY and LLM_PROVIDER=anthropic in backend/docker-compose.local.yml"
            fi
            ;;
        3|[gG]emini)
            read -r -p "  Gemini API key: " gemini_key
            if [[ -n "$gemini_key" ]]; then
                # The example file has an OPENAI_API_KEY line; replace it with
                # the Gemini key and insert LLM_PROVIDER=gemini above it.
                python3 - "$BACKEND_DIR/docker-compose.local.yml" "$gemini_key" <<'PYEOF'
import sys

path, key = sys.argv[1], sys.argv[2]
with open(path) as f:
    lines = f.readlines()
out = []
for line in lines:
    stripped = line.lstrip()
    if stripped.startswith('- OPENAI_API_KEY='):
        indent = line[: len(line) - len(stripped)]
        out.append(f"{indent}- LLM_PROVIDER=gemini\n")
        out.append(f"{indent}- GEMINI_API_KEY={key}\n")
    else:
        out.append(line)
with open(path, 'w') as f:
    f.writelines(out)
PYEOF
                ok "Gemini API key written to backend/docker-compose.local.yml"
            else
                warn "Skipped — set GEMINI_API_KEY and LLM_PROVIDER=gemini in backend/docker-compose.local.yml"
            fi
            ;;
        4|[cC]ustom)
            local default_url="http://host.docker.internal:11434/v1"
            local default_model="llama3.2:latest"

            read -r -p "  Custom LLM URL [${default_url}]: " custom_url
            custom_url="${custom_url:-$default_url}"

            # Warn if the URL uses localhost as hostname
            if [[ "$custom_url" =~ localhost ]]; then
                warn "URL uses 'localhost' — this will not work from a Docker container."
                warn "Use 'host.docker.internal' to refer to the Docker host from within a container."
                warn "  Example: ${default_url}"
            fi

            read -r -p "  Custom LLM model [${default_model}]: " custom_model
            custom_model="${custom_model:-$default_model}"

            read -r -p "  Custom LLM API key required? (y/N): " api_key_required
            api_key_required="${api_key_required:-n}"

            local custom_api_key=""
            if [[ "$api_key_required" =~ ^[yY]([eE][sS])?$ ]]; then
                read -r -p "  Custom LLM API key: " custom_api_key
            fi

            # Detect OS and handle extra_hosts for Linux
            local os_type
            os_type="$(uname -s)"
            local needs_extra_hosts=false
            if [[ "$os_type" == "Linux" ]] && [[ "$custom_url" =~ host\.docker\.internal ]]; then
                needs_extra_hosts=true
            fi

            python3 - "$BACKEND_DIR/docker-compose.local.yml" "$custom_url" "$custom_model" "$custom_api_key" "$needs_extra_hosts" <<'PYEOF'
import sys

path, url, model, api_key, needs_extra_hosts = sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4], sys.argv[5] == "true"
with open(path) as f:
    lines = f.readlines()

out = []
for line in lines:
    stripped = line.lstrip()
    if stripped.startswith('- OPENAI_API_KEY='):
        indent = line[: len(line) - len(stripped)]
        out.append(f"{indent}- LLM_PROVIDER=custom\n")
        out.append(f"{indent}- CUSTOM_LLM_URL={url}\n")
        out.append(f"{indent}- CUSTOM_LLM_MODEL={model}\n")
        if api_key:
            out.append(f"{indent}- CUSTOM_LLM_API_KEY={api_key}\n")
    else:
        out.append(line)

if needs_extra_hosts:
    # Find the environment block and add extra_hosts after the last env var
    new_lines = []
    in_environment = False
    environment_indent = ""
    last_env_idx = -1
    for i, line in enumerate(out):
        stripped = line.lstrip()
        if 'environment:' in stripped:
            in_environment = True
            environment_indent = line[: len(line) - len(stripped)]
            new_lines.append(line)
            continue
        if in_environment:
            if stripped.startswith('- ') and '=' in stripped:
                last_env_idx = len(new_lines)
                new_lines.append(line)
                continue
            if stripped and not stripped.startswith('#'):
                in_environment = False
            if not stripped:
                new_lines.append(line)
                continue
        new_lines.append(line)

    if last_env_idx >= 0:
        extra_indent = environment_indent + "  "
        new_lines.insert(last_env_idx + 1, f"{extra_indent}extra_hosts:\n")
        new_lines.insert(last_env_idx + 2, f"{extra_indent}  - \"host.docker.internal:host-gateway\"\n")

    with open(path, 'w') as f:
        f.writelines(new_lines)
else:
    with open(path, 'w') as f:
        f.writelines(out)
PYEOF

            if [[ -n "$custom_api_key" ]]; then
                ok "Custom LLM configured in backend/docker-compose.local.yml (URL, model, and API key)"
            else
                ok "Custom LLM configured in backend/docker-compose.local.yml (URL and model)"
            fi

            if [[ "$needs_extra_hosts" == "true" ]]; then
                ok "extra_hosts entry added for host.docker.internal (Linux detected)"
            fi
            ;;
        5|[sS]kip)
            warn "Skipped — set your LLM API key in backend/docker-compose.local.yml"
            ;;
        *)
            read -r -p "  OpenAI API key: " openai_key
            if [[ -n "$openai_key" ]]; then
                set_env_var "OPENAI_API_KEY" "$openai_key" "$BACKEND_DIR/docker-compose.local.yml"
                ok "OpenAI API key written to backend/docker-compose.local.yml"
            else
                warn "Skipped — set OPENAI_API_KEY in backend/docker-compose.local.yml"
            fi
            ;;
    esac
}

# ── step 3.5: transcription route ─────────────────────────────────────────────

choose_transcription_route() {
    echo ""
    echo -e "${BOLD}Transcription route${NC}"
    echo "  Choose how meeting audio is transcribed."
    echo ""
    echo -e "  1) Vexa bot  ${BOLD}(default — server-side bot joins Meet/Teams)${NC}"
    echo ""
    echo "  2) Browser extension  (Chrome extension + WhisperLive — no Vexa)"
    echo "     Load prodtrack-tab-sync-extension/ unpacked in Chrome"
    echo ""
    read -r -p "  Choice [1]: " route_choice
    route_choice="${route_choice:-1}"
    echo ""

    case "$route_choice" in
        2|[eE]xtension*)
            TRANSCRIPTION_ROUTE="extension"
            ;;
        *)
            TRANSCRIPTION_ROUTE="vexa"
            ;;
    esac
}

# ── step 3.6: Vexa deployment (self-hosted vs hosted cloud) ───────────────────

configure_vexa() {
    echo ""
    echo -e "${BOLD}Vexa setup${NC}"
    echo "  Vexa provides the meeting bot and transcription that DNA consumes."
    echo ""
    echo -e "  1) Self-hosted Vexa  ${BOLD}(default — runs locally in Docker)${NC}"
    echo "  2) Hosted Vexa  (api.cloud.vexa.ai)"
    echo ""
    read -r -p "  Choice [1]: " vexa_choice
    vexa_choice="${vexa_choice:-1}"
    echo ""

    case "$vexa_choice" in
        2|[hH]osted|[cC]loud)
            VEXA_HOSTED=true
            set_env_var "VEXA_API_URL" "$VEXA_CLOUD_URL" \
                "$BACKEND_DIR/docker-compose.local.yml"
            ok "Vexa API URL set to ${VEXA_CLOUD_URL}"
            read -r -p "  Vexa cloud API key (from https://www.vexa.ai, or Enter to skip): " vexa_cloud_key
            if [[ -n "$vexa_cloud_key" ]]; then
                set_env_var "VEXA_API_KEY" "$vexa_cloud_key" \
                    "$BACKEND_DIR/docker-compose.local.yml"
                ok "Vexa cloud API key written to backend/docker-compose.local.yml"
            else
                warn "Skipped — set VEXA_API_KEY in backend/docker-compose.local.yml"
            fi
            info "Local Vexa container and transcription-backend setup will be skipped."
            ;;
        *)
            VEXA_HOSTED=false
            ;;
    esac
}

detect_transcription_route() {
    if grep -qE 'DNA_ENABLE_EXTENSION_TRANSCRIPTION=(true|"true")' \
            "$BACKEND_DIR/docker-compose.local.yml" 2>/dev/null; then
        echo "extension"
    else
        echo "vexa"
    fi
}

configure_extension_transcription() {
    echo "  Browser-extension transcription setup:"
    echo "    1. Chrome → Extensions → Developer mode → Load unpacked"
    echo "       Select: prodtrack-tab-sync-extension/"
    echo "    2. Copy the extension ID (32 characters) from chrome://extensions"
    echo ""
    read -r -p "  Extension ID (press Enter to skip and set later): " ext_id
    local default_wl="ws://localhost:9090"
    read -r -p "  WhisperLive WebSocket URL [${default_wl}]: " wl_url
    wl_url="${wl_url:-$default_wl}"

    ensure_env_var "DNA_ENABLE_EXTENSION_TRANSCRIPTION" "true" \
        "$BACKEND_DIR/docker-compose.local.yml"
    ensure_env_var "TRANSCRIPTION_PROVIDER" "browser_extension" \
        "$BACKEND_DIR/docker-compose.local.yml"
    ok "Extension transcription enabled in backend/docker-compose.local.yml"

    # Generate the shared key once and place it in every location that needs it:
    # the backend (validates it on the ingest socket) and the frontend (sends it
    # on activation). The extension gets it via the popup — see print_summary.
    EXTENSION_KEY="$(generate_extension_key)"
    ensure_env_var "DNA_EXTENSION_KEY" "$EXTENSION_KEY" \
        "$BACKEND_DIR/docker-compose.local.yml"
    set_feature_flag "VITE_TRANSCRIPTION_EXTENSION_KEY" "$EXTENSION_KEY" "$FRONTEND_ENV"
    ok "Generated shared extension key → backend/docker-compose.local.yml + frontend/packages/app/.env"

    set_feature_flag "VITE_WHISPERLIVE_URL" "$wl_url" "$FRONTEND_ENV"
    ok "VITE_WHISPERLIVE_URL=${wl_url} in frontend/packages/app/.env"

    if [[ -n "$ext_id" ]]; then
        set_feature_flag "VITE_TRANSCRIPTION_EXTENSION_ID" "$ext_id" "$FRONTEND_ENV"
        set_feature_flag "VITE_PRODTRACK_TAB_SYNC_EXTENSION_ID" "$ext_id" "$FRONTEND_ENV"
        ok "Extension ID written to frontend/packages/app/.env"
    else
        warn "Skipped — set VITE_TRANSCRIPTION_EXTENSION_ID in frontend/packages/app/.env"
    fi
}

# ── step 4: transcription service setup ───────────────────────────────────────

# Append SKIP_TRANSCRIPTION_CHECK=true to docker-compose.local.vexa.yml so
# Vexa starts even without a working transcription backend.
add_skip_transcription_check() {
    python3 - "$BACKEND_DIR/docker-compose.local.vexa.yml" <<'PYEOF'
import sys

path = sys.argv[1]
with open(path) as f:
    lines = f.readlines()

if any('SKIP_TRANSCRIPTION_CHECK' in l for l in lines):
    sys.exit(0)

last_env_idx = -1
for i, line in enumerate(lines):
    stripped = line.lstrip()
    if stripped.startswith('- ') and '=' in stripped:
        last_env_idx = i

if last_env_idx >= 0:
    indent = lines[last_env_idx][: len(lines[last_env_idx]) - len(lines[last_env_idx].lstrip())]
    lines.insert(last_env_idx + 1, f"{indent}- SKIP_TRANSCRIPTION_CHECK=true\n")
    with open(path, 'w') as f:
        f.writelines(lines)
PYEOF
    ok "SKIP_TRANSCRIPTION_CHECK=true added to backend/docker-compose.local.vexa.yml"
}

configure_transcription() {
    echo ""
    echo -e "${BOLD}Transcription service setup${NC}"
    echo "  Vexa needs an OpenAI Whisper-compatible transcription backend."
    echo ""
    echo -e "  1) Remote service via vexa.ai  ${BOLD}(recommended — free tier available)${NC}"
    echo "     Get a free key at: https://cal.com/dmitrygrankin/web?duration=15"
    echo ""
    echo "  2) Self-hosted transcription service"
    echo "     Requires Docker (GPU recommended). Setup guide:"
    echo "     https://github.com/Vexa-ai/vexa/tree/main/services/transcription-service"
    echo ""
    echo "  3) Skip for now  (transcription will be disabled at startup)"
    echo "     You can enable it later by editing backend/docker-compose.local.vexa.yml"
    echo ""
    read -r -p "  Choice [1]: " trans_choice
    trans_choice="${trans_choice:-1}"
    echo ""

    case "$trans_choice" in
        2|[sS]elf*)
            echo "  Self-hosted setup steps:"
            echo "    1. git clone https://github.com/Vexa-ai/vexa.git"
            echo "    2. cd vexa/services/transcription-service"
            echo "    3. cp .env.example .env"
            echo "    4. Set API_TOKEN in .env and choose GPU or CPU (DEVICE=cpu for no GPU)"
            echo "    5. docker compose up -d   (or docker compose -f docker-compose.cpu.yml up -d)"
            echo "    6. Wait for: 'Model loaded successfully' in the logs"
            echo ""
            local default_url="http://localhost:8083/v1/audio/transcriptions"
            read -r -p "  Transcription service URL [${default_url}]: " trans_url
            trans_url="${trans_url:-$default_url}"
            read -r -p "  Transcription service API token (your API_TOKEN value, or Enter to skip): " trans_token
            if [[ -n "$trans_token" ]]; then
                set_env_var "TRANSCRIBER_URL" "$trans_url" "$BACKEND_DIR/docker-compose.local.vexa.yml"
                set_env_var "TRANSCRIBER_API_KEY" "$trans_token" "$BACKEND_DIR/docker-compose.local.vexa.yml"
                ok "Self-hosted transcription configured in backend/docker-compose.local.vexa.yml"
            else
                warn "Skipped — set TRANSCRIBER_URL and TRANSCRIBER_API_KEY in backend/docker-compose.local.vexa.yml"
                add_skip_transcription_check
            fi
            ;;
        3|[sS]kip)
            warn "Transcription skipped — Vexa will start without it"
            add_skip_transcription_check
            ;;
        *)
            echo "  Get your free key at: https://cal.com/dmitrygrankin/web?duration=15"
            echo ""
            read -r -p "  Transcription API key (press Enter to skip): " trans_key
            if [[ -n "$trans_key" ]]; then
                set_env_var "TRANSCRIBER_API_KEY" "$trans_key" "$BACKEND_DIR/docker-compose.local.vexa.yml"
                ok "Remote transcription API key written to backend/docker-compose.local.vexa.yml"
            else
                warn "Skipped — set TRANSCRIBER_API_KEY in backend/docker-compose.local.vexa.yml"
                warn "Or add SKIP_TRANSCRIPTION_CHECK=true to disable the startup check"
            fi
            ;;
    esac
}

# ── step 5: production tracking provider ──────────────────────────────────────

configure_prodtrack() {
    echo ""
    echo -e "${BOLD}Production tracking provider${NC}"
    echo "  (Press Enter to skip and fill in manually later)"
    echo ""
    echo -e "  1) Mock  ${BOLD}(default — no ShotGrid seat required)${NC}"
    echo "     Read-only SQLite database with pre-seeded data"
    echo ""
    echo "  2) ShotGrid"
    echo "     Requires a ShotGrid URL, script name, and API key"
    echo ""
    read -r -p "  Choice [1]: " pt_choice
    pt_choice="${pt_choice:-1}"
    echo ""

    case "$pt_choice" in
        2|[sS]hot*)
            read -r -p "  ShotGrid URL (e.g. https://yoursite.shotgrid.autodesk.com): " sg_url
            read -r -p "  ShotGrid script name: " sg_script
            read -r -p "  ShotGrid API key: " sg_key
            if [[ -n "$sg_url" && -n "$sg_script" && -n "$sg_key" ]]; then
                set_env_var "PRODTRACK_PROVIDER" "shotgrid" "$BACKEND_DIR/docker-compose.local.yml"
                set_env_var "SHOTGRID_URL" "$sg_url" "$BACKEND_DIR/docker-compose.local.yml"
                set_env_var "SHOTGRID_SCRIPT_NAME" "$sg_script" "$BACKEND_DIR/docker-compose.local.yml"
                set_env_var "SHOTGRID_API_KEY" "$sg_key" "$BACKEND_DIR/docker-compose.local.yml"
                ok "ShotGrid configured in backend/docker-compose.local.yml"
            else
                warn "Skipped — set PRODTRACK_PROVIDER=shotgrid and SHOTGRID_URL, SHOTGRID_SCRIPT_NAME, SHOTGRID_API_KEY in backend/docker-compose.local.yml"
            fi
            ;;
        *)
            set_env_var "PRODTRACK_PROVIDER" "mock" "$BACKEND_DIR/docker-compose.local.yml"
            ok "Mock production tracking provider configured"
            ;;
    esac
}

# ── step 6: frontend feature flags ────────────────────────────────────────────

# Walk In Review → Transcription → AI (outer doll to inner), enforcing the
# cascade: forcing an outer feature off forces the inner ones off too.
configure_feature_flags_individually() {
    echo "  For each feature choose: [o]n, o[f]f, or [u]ser-controlled (Enter)."
    echo ""

    local in_review trans ai

    read -r -p "  In Review:     [o]n / o[f]f / [u]ser-controlled [u]: " in_review
    in_review="$(normalize_flag "${in_review:-u}")"
    apply_feature_flag "VITE_FEATURE_IN_REVIEW" "In Review" "$in_review"

    # Transcription needs In Review, so a forced-off In Review forces it off.
    if [[ "$in_review" == "false" ]]; then
        trans="false"
        apply_feature_flag "VITE_FEATURE_TRANSCRIPTION" "Transcription" "$trans" "requires In Review"
    else
        read -r -p "  Transcription: [o]n / o[f]f / [u]ser-controlled [u]: " trans
        trans="$(normalize_flag "${trans:-u}")"
        apply_feature_flag "VITE_FEATURE_TRANSCRIPTION" "Transcription" "$trans"
    fi

    # AI needs Transcription, so a forced-off Transcription forces it off.
    if [[ "$trans" == "false" ]]; then
        ai="false"
        apply_feature_flag "VITE_FEATURE_AI" "AI" "$ai" "requires Transcription"
    else
        read -r -p "  AI:            [o]n / o[f]f / [u]ser-controlled [u]: " ai
        ai="$(normalize_flag "${ai:-u}")"
        apply_feature_flag "VITE_FEATURE_AI" "AI" "$ai"
    fi
}

configure_feature_flags() {
    echo ""
    echo -e "${BOLD}Frontend feature flags (pipeline-level overrides)${NC}"
    echo "  Optionally lock In Review, Transcription, and AI for ALL users by"
    echo "  setting VITE_FEATURE_* in frontend/packages/app/.env. A locked feature"
    echo "  shows a grayed-out toggle in Settings; left unset, each user decides"
    echo "  for themselves (all three default ON)."
    echo ""
    echo "  They cascade like russian dolls — AI needs Transcription, and"
    echo "  Transcription needs In Review:"
    echo "    AI  ⊆  Transcription  ⊆  In Review"
    echo "  Forcing an outer feature off also forces the inner ones off."
    echo ""
    echo -e "  1) Leave all user-controlled  ${BOLD}(default)${NC}"
    echo "  2) Force all three ON for everyone"
    echo "  3) Force all three OFF for everyone"
    echo "  4) Configure each feature individually"
    echo ""
    read -r -p "  Choice [1]: " ff_choice
    ff_choice="${ff_choice:-1}"
    echo ""

    case "$ff_choice" in
        2)
            apply_feature_flag "VITE_FEATURE_IN_REVIEW"    "In Review"     "true"
            apply_feature_flag "VITE_FEATURE_TRANSCRIPTION" "Transcription" "true"
            apply_feature_flag "VITE_FEATURE_AI"            "AI"            "true"
            ;;
        3)
            apply_feature_flag "VITE_FEATURE_IN_REVIEW"    "In Review"     "false"
            apply_feature_flag "VITE_FEATURE_TRANSCRIPTION" "Transcription" "false"
            apply_feature_flag "VITE_FEATURE_AI"            "AI"            "false"
            ;;
        4)
            configure_feature_flags_individually
            ;;
        *)
            ok "Feature flags left user-controlled (VITE_FEATURE_* stay unset)"
            ;;
    esac
}

# ── step 7: frontend dependencies ─────────────────────────────────────────────

install_frontend() {
    info "Installing frontend dependencies..."
    (cd "$FRONTEND_DIR" && npm install)
    ok "Frontend dependencies installed"
}

# ── step 6: Vexa API key generation ───────────────────────────────────────────

bootstrap_vexa() {
    local compose_cmd
    compose_cmd="$(get_compose_cmd)"

    info "Starting Vexa services to generate a local API key..."
    (
        cd "$BACKEND_DIR"
        $compose_cmd \
            -f docker-compose.vexa.yml \
            -f docker-compose.local.vexa.yml \
            up -d --force-recreate --remove-orphans vexa vexa-db
    )

    info "Waiting for Vexa admin API on :8057 (may take ~30 s on first pull)..."
    local retries=40
    until curl -sf \
            -H "X-Admin-API-Key: ${VEXA_ADMIN_TOKEN}" \
            "${VEXA_ADMIN_URL}/admin/users" \
            -o /dev/null 2>/dev/null; do
        retries=$((retries - 1))
        if [[ $retries -le 0 ]]; then
            if docker logs vexa 2>&1 | grep -q 'Transcription service returned HTTP'; then
                die "Vexa failed to start — transcription API key was rejected.\n       Add SKIP_TRANSCRIPTION_CHECK=true to backend/docker-compose.local.vexa.yml and re-run."
            fi
            die "Vexa admin API did not become ready in time. Run: docker logs vexa"
        fi
        sleep 3
    done
    ok "Vexa admin API is ready"

    info "Creating local Vexa user (${VEXA_LOCAL_EMAIL})..."

    local tmpfile
    tmpfile="$(mktemp)"

    local http_code
    http_code="$(curl -s -o "$tmpfile" -w "%{http_code}" \
        -X POST \
        -H "X-Admin-API-Key: ${VEXA_ADMIN_TOKEN}" \
        -H "Content-Type: application/json" \
        -d "{\"email\":\"${VEXA_LOCAL_EMAIL}\",\"name\":\"DNA Local Dev\"}" \
        "${VEXA_ADMIN_URL}/admin/users")"
    local create_response
    create_response="$(cat "$tmpfile")"
    rm -f "$tmpfile"

    local user_id
    if [[ "$http_code" == "200" || "$http_code" == "201" ]]; then
        user_id="$(echo "$create_response" \
            | python3 -c "import sys,json; print(json.load(sys.stdin)['id'])")"
        ok "Vexa user created (id: ${user_id})"
    elif [[ "$http_code" == "409" ]]; then
        warn "User already exists — fetching existing record..."
        local list_response
        list_response="$(curl -sf \
            -H "X-Admin-API-Key: ${VEXA_ADMIN_TOKEN}" \
            "${VEXA_ADMIN_URL}/admin/users")"
        user_id="$(echo "$list_response" | python3 - "$VEXA_LOCAL_EMAIL" <<'PYEOF'
import sys, json
users = json.load(sys.stdin)
email = sys.argv[1]
match = [u for u in users if u.get("email") == email]
print((match or users)[0]["id"])
PYEOF
)"
        ok "Found existing Vexa user (id: ${user_id})"
    else
        rm -f "$tmpfile"
        die "Unexpected response from Vexa admin API (HTTP ${http_code}): ${create_response}"
    fi

    info "Generating Vexa API token..."
    local token_response vexa_api_key
    token_response="$(curl -sf \
        -X POST \
        -H "X-Admin-API-Key: ${VEXA_ADMIN_TOKEN}" \
        "${VEXA_ADMIN_URL}/admin/users/${user_id}/tokens")"
    vexa_api_key="$(echo "$token_response" \
        | python3 -c "import sys,json; print(json.load(sys.stdin)['token'])")"
    ok "Vexa API key generated"

    set_env_var "VEXA_API_KEY" "$vexa_api_key" "$BACKEND_DIR/docker-compose.local.yml"
    ok "Vexa API key written to backend/docker-compose.local.yml"
}

# ── step 7: start the full stack ───────────────────────────────────────────────

start_full_stack() {
    local route="${1:-${TRANSCRIPTION_ROUTE:-vexa}}"

    if [[ "$route" == "extension" ]]; then
        info "Starting the DNA stack with WhisperLive (no Vexa — first run may take a few minutes)..."
        (cd "$BACKEND_DIR" && make start-local-extension-detached)
        ok "All services started"
        return
    fi

    local compose_cmd
    compose_cmd="$(get_compose_cmd)"

    # Re-derive hosting from the configured API URL so --start (which skips the
    # interactive prompts) starts the right set of containers.
    if grep -qF "VEXA_API_URL=${VEXA_CLOUD_URL}" \
            "$BACKEND_DIR/docker-compose.local.yml" 2>/dev/null; then
        VEXA_HOSTED=true
    fi

    # Hosted Vexa runs no local vexa/vexa-db/vexa-dashboard containers, so omit
    # the Vexa compose files entirely (order otherwise matches the original).
    local -a compose_files=(-f docker-compose.yml)
    [[ "$VEXA_HOSTED" != "true" ]] && compose_files+=(-f docker-compose.vexa.yml)
    compose_files+=(-f docker-compose.debug.yml -f docker-compose.local.yml)
    [[ "$VEXA_HOSTED" != "true" ]] && compose_files+=(-f docker-compose.local.vexa.yml)

    info "Starting the full DNA stack (first run builds containers — this may take a few minutes)..."
    (
        cd "$BACKEND_DIR"
        $compose_cmd "${compose_files[@]}" \
            up --build -d --force-recreate --remove-orphans
    )
    ok "All services started"
}

# ── step 8: wait for DNA API ───────────────────────────────────────────────────

wait_for_dna() {
    local route="${1:-${TRANSCRIPTION_ROUTE:-vexa}}"
    local logs_target="logs-local-vexa"
    [[ "$route" == "extension" ]] && logs_target="logs-local-extension"

    info "Waiting for DNA API on :8000 (may take a moment while containers start)..."
    local retries=40
    until curl -sf "http://localhost:8000/docs" -o /dev/null 2>/dev/null; do
        retries=$((retries - 1))
        if [[ $retries -le 0 ]]; then
            die "DNA API did not become ready in time. Check logs: cd backend && make ${logs_target}"
        fi
        sleep 3
    done
    ok "DNA API is ready"
}

# ── print summary ──────────────────────────────────────────────────────────────

print_summary() {
    local label="$1"
    local route="${2:-${TRANSCRIPTION_ROUTE:-vexa}}"
    echo ""
    echo -e "${BOLD}${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e "${BOLD}${GREEN}  ${label}${NC}"
    echo -e "${BOLD}${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo ""
    echo "  Running services:"
    echo "    DNA API      →  http://localhost:8000"
    echo "    API Docs     →  http://localhost:8000/docs"
    if [[ "$route" == "extension" ]]; then
        echo "    WhisperLive  →  ws://localhost:9090"
    elif [[ "$VEXA_HOSTED" == "true" ]]; then
        echo "    Vexa         →  ${VEXA_CLOUD_URL} (hosted)"
    else
        echo "    Vexa Admin   →  http://localhost:3001"
    fi
    echo ""
    echo "  To start the frontend (in a new terminal):"
    echo "    cd frontend && npm run dev"
    echo "    App  →  http://localhost:5173"
    echo ""
    echo "  To follow backend logs:"
    if [[ "$route" == "extension" ]]; then
        echo "    cd backend && make logs-local-extension"
    else
        echo "    cd backend && make logs-local-vexa"
    fi
    echo ""
    if [[ "$route" == "extension" ]]; then
        local ext_key
        ext_key="$(current_extension_key)"
        echo "  Browser-extension transcription:"
        echo "    1. Ensure prodtrack-tab-sync-extension/ is loaded in Chrome"
        echo "    2. Confirm VITE_TRANSCRIPTION_EXTENSION_ID in frontend/packages/app/.env"
        if [[ -n "$ext_key" ]]; then
            echo -e "    3. Open the extension popup and paste this DNA key, then Save:"
            echo -e "         ${BOLD}${ext_key}${NC}"
            echo "       (already set in the backend + frontend env for you)"
        else
            echo "    3. Paste your DNA key into the extension popup and Save"
        fi
        echo "    4. In DNA, open a playlist → Transcribe via Extension → grant Meet tab permission"
        echo "    Details: backend/docs/TRANSCRIPTION_PIPELINE.md"
        echo ""
    else
        echo "  Optional — browser-extension transcription route (instead of the Vexa bot):"
        echo "    Re-run ./bootstrap.sh and choose option 2 under Transcription route."
        echo "    Details: backend/docs/TRANSCRIPTION_PIPELINE.md"
        echo ""
    fi
    local needs_attention=false
    if grep -q 'your-openai-api-key\|GEMINI_API_KEY=\*\*\|OPENAI_API_KEY=\*\*' \
            "$BACKEND_DIR/docker-compose.local.yml" 2>/dev/null; then
        needs_attention=true
        echo -e "  ${YELLOW}Action needed:${NC} fill in your LLM API key in:"
        echo "    backend/docker-compose.local.yml"
        echo ""
    fi
    if [[ "$VEXA_HOSTED" == "true" ]]; then
        if grep -q 'VEXA_API_KEY=\*\*' \
                "$BACKEND_DIR/docker-compose.local.yml" 2>/dev/null; then
            needs_attention=true
            echo -e "  ${YELLOW}Action needed:${NC} fill in your hosted Vexa API key in:"
            echo "    backend/docker-compose.local.yml  (VEXA_API_KEY)"
            echo "  Get a key at: https://www.vexa.ai"
            echo ""
        fi
    elif [[ "$route" == "vexa" ]] && grep -q 'TRANSCRIBER_API_KEY=\*\*' \
            "$BACKEND_DIR/docker-compose.local.vexa.yml" 2>/dev/null; then
        needs_attention=true
        echo -e "  ${YELLOW}Action needed:${NC} fill in your transcription API key in:"
        echo "    backend/docker-compose.local.vexa.yml"
        echo "  Get a free key at: https://cal.com/dmitrygrankin/web?duration=15"
        echo ""
    fi
    if [[ "$route" == "extension" ]] && ! grep -qE '^VITE_TRANSCRIPTION_EXTENSION_ID=[^[:space:]]+$' \
            "$FRONTEND_ENV" 2>/dev/null; then
        needs_attention=true
        echo -e "  ${YELLOW}Action needed:${NC} set your Chrome extension ID in:"
        echo "    frontend/packages/app/.env  (VITE_TRANSCRIPTION_EXTENSION_ID)"
        echo ""
    fi
    if [[ "$needs_attention" == "true" ]]; then
        echo "  After updating, restart with:  ./bootstrap.sh --start"
        echo ""
    fi
}

# ── main ───────────────────────────────────────────────────────────────────────

main() {
    local start_only=false
    for arg in "$@"; do
        case "$arg" in
            --start) start_only=true ;;
            *) die "Unknown argument: $arg. Usage: ./bootstrap.sh [--start]" ;;
        esac
    done

    echo ""
    if [[ "$start_only" == "true" ]]; then
        echo -e "${BOLD}${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
        echo -e "${BOLD}${BLUE}  DNA — Start${NC}"
        echo -e "${BOLD}${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
        echo ""
        check_prerequisites
        echo ""
        TRANSCRIPTION_ROUTE="$(detect_transcription_route)"
        start_full_stack "$TRANSCRIPTION_ROUTE"
        echo ""
        wait_for_dna "$TRANSCRIPTION_ROUTE"
        print_summary "DNA is running!" "$TRANSCRIPTION_ROUTE"
    else
        echo -e "${BOLD}${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
        echo -e "${BOLD}${BLUE}  DNA — Bootstrap${NC}"
        echo -e "${BOLD}${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
        echo ""
        check_prerequisites
        echo ""
        choose_transcription_route
        copy_config_files
        echo ""
        configure_llm
        if [[ "$TRANSCRIPTION_ROUTE" == "extension" ]]; then
            configure_extension_transcription
        else
            configure_vexa
            if [[ "$VEXA_HOSTED" != "true" ]]; then
                configure_transcription
            fi
        fi
        configure_prodtrack
        configure_feature_flags
        install_frontend
        echo ""
        if [[ "$TRANSCRIPTION_ROUTE" == "extension" ]]; then
            info "Skipping Vexa bootstrap (browser-extension transcription route)"
        elif [[ "$VEXA_HOSTED" != "true" ]]; then
            bootstrap_vexa
            echo ""
        fi
        start_full_stack "$TRANSCRIPTION_ROUTE"
        echo ""
        wait_for_dna "$TRANSCRIPTION_ROUTE"
        print_summary "Bootstrap complete!" "$TRANSCRIPTION_ROUTE"
    fi
}

main "$@"
