# Generated by Django 5.2.5 on 2025-08-21 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Schedule",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("starttime", models.DateTimeField()),
                ("endtime", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("inprogress", "In Progress"),
                            ("failed", "Failed"),
                            ("done", "Done"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("metadata", models.JSONField()),
                ("playlistid", models.CharField(max_length=255)),
                ("meetingtype", models.CharField(default="meet", max_length=50)),
            ],
        ),
    ]
