import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Sidebar for the frontend docs (the default docs instance, served at /docs).
 * Backend API docs live in a separate instance - see sidebarsApi.ts.
 */
const sidebars: SidebarsConfig = {
  // Generated from the docs/ folder structure.
  frontendSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
